# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

app_identifier(ENV['APP_IDENTIFIER'])
team_id(ENV['APPLE_STORE_TEAM_ID'])

# App information
app_version("1.0.0")
submission_information({
    export_compliance_uses_encryption: false,
    export_compliance_encryption_updated: false,
    content_rights_contains_third_party_content: false,
    add_id_info_uses_idfa: false
})

# Metadata and screenshots
skip_metadata(false)
skip_screenshots(false)
force(true) # Skip verification of HTML preview file

# Submission options
submit_for_review(true)
automatic_release(false)
price_tier(0) # Free app

# Categories
primary_category("GRAPHICS_DESIGN")
secondary_category("PRODUCTIVITY") 

# Rating settings
app_rating_config_path("./fastlane/metadata/app_rating_config.json") 